### PR TITLE
Work-in-progress: Filter data fields

### PR DESCRIPTION
**Pull request by coreymckrill**
The goal here is to create a standardized way to redact or remove fields from raw report data before it is cached. The use case is that some reports may contain data that is sensitive from a privacy standpoint, and while it might be necessary to include it for WPCS staff, it should be excluded from public output.

The approach here is to run the data rows through a "safelist" (intentionally using this [instead of "whitelist"/"blacklist"](https://twitter.com/secnerdette/status/898314208097427457)) and strip out fields that aren't in the list. This also adds a `public` option flag to reports that can be used to determine whether filtering is necessary and also filtered vs non-filtered cached data.

Filtering data fields could have other uses as well, such as normalization or sanitization.

### CODE REVIEW

**Comment by iandunn** [comment]
👍 

So far, it doesn't look like there are any private fields. If there were, are you thinking it'd look something like the following? Or would it be different?

```php
protected function filter_data_fields( array $data ) {
		$safelist = array(
			'name'          => '',
			'urlname'       => '',
			'city'          => '',
			'state'         => '',
			'country'       => '',
			'lat'           => 0,
			'lon'           => 0,
			'member_count'  => 0,
			'founded_date'  => 0,
			'pro_join_date' => 0,
		);

		if ( $this->options['public'] ) {
			$safelist = array_merge( $safelist, array(
				'foo' => 0,
				'bar' => '',
			) );
		}

		array_walk( $data, function ( &$group ) use ( $safelist ) {
			$group = shortcode_atts( $safelist, $group );
		} );

		return $data;
	}
```

**Comment by iandunn** [comment]
Doh, I meant, `if ( current_user_can( 'manage_network' ) ) { add private items }`...

**Comment by iandunn** [comment]
Something like this might make the code a bit more self-documenting, and less prone to human error:

```php
$public_fields = array( 'foo', 'bar', 'baz' );
$private_fields = array( 'qux', 'qin', 'qoy' );

$safelist = $public_fields;
if ( current_user_can( 'manage_network' ) ) {
    $safelist = array_merge( $safelist, $private_fields );
}
```

This way, the fields are explicitly labeled `public` and `private`, so if a dev who isn't familiar with the function wants to add a new field, it's very obvious that they have to decide if it should be public or not. If it just says "safelist" on it's own, they may not realize what the criteria are for something being safe. They may assume that it's just meant to be a list of known fields.

**Comment by coreymckrill** [comment]
Good point. I like `public/private` better.

**Pull request merged**
